### PR TITLE
(GH-17) Fix typo in filename

### LINKED ISSUE #17: Typo in Import-PQDeployPackage.ps1 filename
The filenames should match the functions inside. The `Import-PQDeployPackage.ps1` file has a typo in its name.

### PR DESCRIPTION
**Pull request by pauby**
Rename file to match function inside.

Fixes #17

### CODE REVIEW

**Comment by Windos** [comment]
@pauby, this looks like a no brainer to me but there's a conflict. Pretty sure a rebase will sort that out quick smart if you have a moment for that?

**Comment by corbob** [comment]
@Windos it looks like @pauby removed the branch from his fork 🤔 

I've checked and it will rebase on master with no problems. So I guess the next steps going forward would be for pauby to recreate the branch on his fork, or for one of us to checkout the PR and push it to our fork and open a new PR. We can discuss this more next week and get this squared away.

**Comment by Windos** [comment]
> @Windos it looks like @pauby removed the branch from his fork 🤔

... That explains why I was having all sorts of issues looking at this yesterday 😅

This'd be a trivial change to recreate in a new PR if required, would be good to get it in regardless of method.

**Comment by gep13** [comment]
@Windos @corbob to me, re-creating this PR is not necessary.

if this were me, I would be doing the following...

Check out the PR branch locally onto my machine:

```
gh pr checkout 18
```
NOTE: This assuming that you are using the GH CLI (If you aren't, you really should be 😄 ) `choco install gh` or `brew install gh`, pick your poison!

Rebase the PR:

```
git rebase master
```

This will bring the PR up to the head of the master branch, however, I am not sure if this is where it is meant to be.  In all likelihood, this PR should be targetting the develop branch, so then I would be doing the following:

```
git rebase --onto develop master
```

NOTE: The above assumes that you are still on the `fix/filename-match-function` branch.

From there, I would be merging the branch locally into the develop branch, and then pushing back to my upstream (gep13/ChocoCCM) and origin (chocolatey/ChocoCCM):

```
git checkout develop
git merge --no-ff fix/filename-match-function
git push upstream
git push origin
```

With all of that done, GitHub will be confused, so we can go ahead and close this PR, but the original person doing the contribution (in this case @pauby) will still be credited with the work, and everything will be updated accordingly.

Let me know if you have any questions about the above.

**Comment by corbob** [comment]
Thanks for getting this sorted @pauby 

I've merged this into develop following @gep13's steps 😁

**Pull request closed without merging**
